language: perl

sudo: false

notifications:
  email: false

cache:
  directories:
    - ~/perl5

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules
