=pod

=encoding UTF-8

=head1 NAME

IPC::Simple - easy, non-blocking IPC

=head1 VERSION

version 0.01

=head1 SYNOPSIS

  use IPC::Simple;

  my $ssh = IPC::Simple->new(
    cmd  => 'ssh',
    args => [ $host ],
  );

  if ($ssh->launch) {
    $ssh->send('cd $HOME/some/dir');
    $ssh->send('ls -lah');
    $ssh->send('exit');

    while (my $line = $ssh->recv) {
      say $line;
    }
  }

=head1 DESCRIPTION

=head1 EXPORTED CONSTANTS

=head1 METHODS

=head1 new

=head1 METHODS

=head1 DEBUGGING

=head1 AUTHOR

Jeff Ober <sysread@fastmail.fm>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2020 by Jeff Ober.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
